# Generated by Django 2.1 on 2018-10-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_survey', '0002_auto_20181009_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='risposte',
            old_name='numero',
            new_name='numero_domanda',
        ),
        migrations.AlterField(
            model_name='domande',
            name='lingua',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='domande',
            name='suggerimento',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='cinque',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='diciannove',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='diciassette',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='diciotto',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='dieci',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='dodici',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='due',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='idoneo',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='lingua',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='nove',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='otto',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='quattordici',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='quattro',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='quindici',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='sedici',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='sei',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='sette',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='tre',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='tredici',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='undici',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='uno',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='venti',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='venticinque',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='ventidue',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='ventiquattro',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='ventitre',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='ventuno',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='risposte',
            name='booleano',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='risposte',
            name='data',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='risposte',
            name='intero',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='risposte',
            name='lingua',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='risposte',
            name='testo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
