# Generated by Django 2.1 on 2018-10-13 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_survey', '0007_auto_20181012_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logtable',
            name='when',
        ),
        migrations.AddField(
            model_name='logtable',
            name='session',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l10',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l12',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l13',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l14',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l16',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l19',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l20',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l21',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l23',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l24',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l25',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l6',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l7',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='l8',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='lang',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='valid',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
