# Generated by Django 2.1 on 2018-10-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_survey', '0008_auto_20181013_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='lang',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='session',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
