# Generated by Django 2.1 on 2018-10-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_survey', '0009_auto_20181014_0018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logtable',
        ),
    ]
