# Generated by Django 2.1 on 2018-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domande',
            name='categoria',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='domande',
            name='lingua',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='logtable',
            name='lingua',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='risposte',
            name='lingua',
            field=models.CharField(max_length=30),
        ),
    ]
