# Generated by Django 2.1 on 2018-10-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_survey', '0004_auto_20181009_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risposte',
            name='data',
        ),
        migrations.RemoveField(
            model_name='risposte',
            name='intero',
        ),
        migrations.AddField(
            model_name='risposte',
            name='barra',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='risposte',
            name='immagine',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
