# Generated by Django 2.1 on 2018-10-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_survey', '0006_auto_20181012_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='domande',
            name='barra_img',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='domande',
            name='immagine',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
